apiVersion: v1
kind: List
items:  
# pvc
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: btc-data
    namespace: sganis-dev
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
      volume.kubernetes.io/storage-provisioner: efs.csi.aws.com
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: efs-sc
    volumeMode: Filesystem

# deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: btc
    namespace: sganis-dev
    labels:
      app: btc
      app.kubernetes.io/part-of: btc
    # annotations:
    #   app.openshift.io/connects-to: >-
    #     [{"apiVersion":"apps/v1","kind":"Deployment","name":"btc"}]
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: btc
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    template:
      metadata:
        annotations:
          openshift.openshift.io/restartedAt: "2025-04-12T10:00:00.000Z"
        labels:
          app: btc
      spec:
        containers:
          - name: btc
            image: image-registry.openshift-image-registry.svc:5000/sganis-dev/btc:latest
            imagePullPolicy: Always
            args:
              - "-testnet=1"
              - "-prune=550"
              - "-server=1"
              - "-rpcbind=0.0.0.0"
              - "-rpcallowip=0.0.0.0/0"
              - "-rpcuser=bitcoin"
              - "-rpcpassword=secret"
            ports:
              - containerPort: 18332
                protocol: TCP
              - containerPort: 18333
                protocol: TCP
            volumeMounts:
              - name: btc-data
                mountPath: /home/bitcoin/.bitcoin
            resources: 
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 256Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        volumes:
          - name: btc-data
            persistentVolumeClaim:
              claimName: btc-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30

# buldconfig
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: btc
    name: btc
    namespace: sganis-dev
  spec:
    failedBuildsHistoryLimit: 3
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: btc:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /btc
      git:
        ref: main
        uri: https://github.com/sganis/openshift.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    successfulBuildsHistoryLimit: 3
    triggers:
    - type: ConfigChange

# image
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: btc
    name: btc
    namespace: sganis-dev
  spec:
    lookupPolicy:
      local: false

# svc-bitcoin.yaml
- apiVersion: v1
  kind: Service
  metadata:
    name: btc
    namespace: sganis-dev
    labels:
      app: btc
  spec:
    selector:
      app: btc
    ports:
      - name: rpc
        port: 18332
        targetPort: 18332
      - name: p2p
        port: 18333
        targetPort: 18333
    type: ClusterIP
