apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nolock"},"name":"nolock","namespace":"sganis-dev"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nolock"}},"template":{"metadata":{"labels":{"app":"nolock"}},"spec":{"containers":[{"env":[{"name":"SERVICE_URL","value":"http://service:5001"},{"name":"DB_PASSWORD","value":"1234"}],"image":"image-registry.openshift-image-registry.svc:5000/sganis-dev/nolock:latest","imagePullPolicy":"Always","name":"nolock","ports":[{"containerPort":5000}],"volumeMounts":[{"mountPath":"/app/data","name":"shared-storage"}]}],"restartPolicy":"Always","volumes":[{"name":"shared-storage","persistentVolumeClaim":{"claimName":"shared-storage"}}]}}}}
  creationTimestamp: "2025-03-04T08:24:00Z"
  generation: 5
  labels:
    app: nolock
  name: nolock
  namespace: sganis-dev
  resourceVersion: "357074840"
  uid: 186f59d2-496e-4332-8fee-7357bee3e788
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nolock
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.openshift.io/restartedAt: "2025-03-04T08:53:59.760Z"
      creationTimestamp: null
      labels:
        app: nolock
    spec:
      containers:
      - env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: nolock-db-password
        image: image-registry.openshift-image-registry.svc:5000/sganis-dev/nolock:latest
        imagePullPolicy: Always
        name: nolock
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/data
          name: shared-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-storage
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-03-04T08:24:00Z"
    lastUpdateTime: "2025-03-04T08:54:05Z"
    message: ReplicaSet "nolock-886c9dff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-03-04T08:55:41Z"
    lastUpdateTime: "2025-03-04T08:55:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
