# .github/workflows/openshift.yml
name: Trigger OpenShift Build
on:
  push:
    branches:
      - main
env:
  URL: https://api.rm1.0a51.p1.openshiftapps.com:6443/apis/build.openshift.io/v1/namespaces/sganis-dev/buildconfigs
  TOKEN: ${{ secrets.OPENSHIFT_BUILDER_TOKEN }}

jobs:
  trigger-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Required to get the previous commit

      - name: Get list of changed files
        id: changes
        run: |
          git diff --name-only HEAD^ HEAD > changed.txt
          echo "CHANGED_FILES=$(cat changed.txt | xargs)" >> $GITHUB_ENV

      - name: Trigger frontend BuildConfig if frontend changed
        if: contains(env.CHANGED_FILES, 'frontend/')
        run: |
          curl -k -X POST \
            "$URL/frontend/instantiate" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{ 
              "kind": "BuildRequest", 
              "apiVersion": "build.openshift.io/v1", 
              "metadata": { "name": "frontend" }
              }'

  trigger-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Required to get the previous commit

      - name: Get list of changed files
        id: changes
        run: |
          git diff --name-only HEAD^ HEAD > changed.txt
          echo "CHANGED_FILES=$(cat changed.txt | xargs)" >> $GITHUB_ENV

      - name: Trigger worker BuildConfig if worker changed
        if: contains(env.CHANGED_FILES, 'worker/')
        run: |
          curl -k -X POST \
            "$URL/worker/instantiate" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{ 
              "kind": "BuildRequest", 
              "apiVersion": "build.openshift.io/v1", 
              "metadata": { "name": "worker" } 
            }'
            
  trigger-btc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Required to get the previous commit

      - name: Get list of changed files
        id: changes
        run: |
          git diff --name-only HEAD^ HEAD > changed.txt
          echo "CHANGED_FILES=$(cat changed.txt | xargs)" >> $GITHUB_ENV

      - name: Trigger btc BuildConfig if btc changed
        if: contains(env.CHANGED_FILES, 'btc/')
        run: |
          curl -k -X POST \
            "$URL/btc/instantiate" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{ 
              "kind": "BuildRequest", 
              "apiVersion": "build.openshift.io/v1", 
              "metadata": { "name": "btc" } 
            }'

            trigger-btc:
              runs-on: ubuntu-latest
              steps:
                - name: Check out code
                  uses: actions/checkout@v4
                  with:
                    fetch-depth: 2  # Required to get the previous commit
          
                - name: Get list of changed files
                  id: changes
                  run: |
                    git diff --name-only HEAD^ HEAD > changed.txt
                    echo "CHANGED_FILES=$(cat changed.txt | xargs)" >> $GITHUB_ENV
          
                - name: Trigger btc BuildConfig if btc changed
                  if: contains(env.CHANGED_FILES, 'btc/')
                  run: |
                    curl -k -X POST \
                      "$URL/btc/instantiate" \
                      -H "Authorization: Bearer $TOKEN" \
                      -H "Content-Type: application/json" \
                      -d '{ 
                        "kind": "BuildRequest", 
                        "apiVersion": "build.openshift.io/v1", 
                        "metadata": { "name": "btc" } 
                      }'
                                            